name: Java CI with Gradle (Groovy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1.2.5
        with:
            distribution: 'graalvm'
            java-version: ${{ matrix.java }}
            github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --continue
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Build Artifacts
          path: |
            **/build/reports
